[package]
name = "rustpart"
version = "0.1.0"
authors = ["21oavery <21oavery@ga.hiltoncsd.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.13.1"